title: Heinrich Lee Yu
description: >
  **Heinrich Lee Yu**
  Ruby, Elixir, Ember.js software developer from Cebu, Philippines
copyright: 2018
sass:
  sass_dir: assets/sass
url: https://engwan.me
disqus_shortname:
facebook_username:
twitter_username:
linkedin_username: "engwan"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "engwan"
feed_icon:
email: "hleeyu@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
